"$schema" = 'https://starship.rs/config-schema.json'

format = """
$sudo\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
\
$fill\
\
$c\
$cmake\
$cobol\
$dart\
$dotnet\
$fortran\
$golang\
$haskell\
$java\
$lua\
$nodejs\
$perl\
$php\
$python\
$ruby\
$rust\
$swift\
\
$nix_shell\
$aws\
$gcloud\
$openstack\
$azure\
\
$direnv\
$env_var\
$custom\
$cmd_duration\
\
$line_break\
\
$jobs\
$battery\
$status\
$container\
$character"""

[fill]
style = 'bright-black'

[sudo]
disabled = false
symbol = '󰒃'
format = '[$symbol]($style) '
style = 'bold yellow'

[username]
show_always = true
format = '[$user]($style) [|](bright-black) '

[hostname]
ssh_only = false
ssh_symbol = ' '
format = '[$ssh_symbol$hostname]($style) [|](bright-black) '
style = 'bold green'

[directory]
read_only = ' 󰌾'
style = 'bold blue'
truncate_to_repo = false
truncation_length = 3
truncation_symbol = '…/'

[cmd_duration]
format = ' 󱎫 [$duration]($style) '
style = 'white'
min_time = 1_000





[aws]
symbol = ' '




[docker_context]
symbol = ' '
format = 'via [$symbol$context]($style) '

[git_branch]
symbol = ' '

[git_commit]
tag_symbol = '  '

[memory_usage]
symbol = '󰍛 '

[nix_shell]
symbol = ' '
format = ' [$symbol$state( \($name\))]($style) [|](bright-black)'

[status]
symbol = ' '
disabled = false






[c]
symbol = 'C '
format = ' ([$symbol($version(-$name))]($style) [|](bright-black))'

[cpp]
symbol = 'C++ '
format = ' ([$symbol($version(-$name))]($style) [|](bright-black))'

[cmake]
symbol = 'cmake '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[cobol]
symbol = 'cobol '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[dart]
symbol = 'dart '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[dotnet]
symbol = '.NET '
format = ' ([$symbol($version )(target $tfm )]($style)[|](bright-black))'

[fortran]
symbol = 'fortran '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[golang]
symbol = 'go '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[haskell]
symbol = 'haskell '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[java]
symbol = 'java '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[lua]
symbol = 'lua '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[nodejs]
symbol = 'nodejs '
format = ' ([$symbol($version)]($style) [|](bright-black))'




[package]
symbol = '󰏗 '
format = '(is [$symbol$version]($style) )'




[perl]
symbol = 'pl '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[php]
symbol = 'php '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[python]
symbol = 'py '
format = ' ([${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)[|](bright-black))'

[ruby]
symbol = 'rb '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[rust]
symbol = 'rs '
format = ' ([$symbol($version)]($style) [|](bright-black))'

[swift]
symbol = 'swift '
format = ' ([$symbol($version)]($style) [|](bright-black))'
